### ISSUE TITLE
Tweaking AppVeyor and build

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/ClientDependency#3]
@ahoefling I may have been too hasty to merge #2 but no harm done. There are some additional details to iron out:

1. I think we should change the NuGet name. Maybe Dnn.ClientDependency? This would prevent running into problem with us deploying a version numbered lower than the official. Without a new name our package would be constantly replaced.
1. I assume that you took the version from AppVeyor but I notice that it's out of sync from how ClientDependency is actually tagged and released. The last "inherited" commit would be `20854c3` which places it somewhere between `1.9.1` and `1.9.2`. Hence, the former is what we should use IMO

**Comment by SkyeHoefling** [comment]
Follow up items:

* Update nuget package file to produce Dnn.ClientDependency so it is different from the root package.

Questions:

* The versioning scheme I was not 100% sure because I didn't get any direction on what we wanted to. Since this is our fork I can just reset the versioning to be 1.0.0.0 or whatever your advise on

@tpluscode Once I get direction on the versioning I'll submit a new pull request

Related: dnnsoftware/Dnn.Platform#2061

**Comment by tpluscode** [comment]
Thanks!

I think it makes sense to keep the numbering close to the original albeit troublesome in case we want to add some changes and keep clean Sem Ver. On the other hand we shall diverge from the original only ever so often. Do you have any opinion?

**Comment by bdukes** [comment]
I would lean towards following their versioning (thinking of it as the official 1.9.2 plus DNN-specific additions).  We only run into trouble here if we want to release multiple updates out-of-sync with their releases, which IMO seems the least of the possible sources of confusion.

**Comment by SkyeHoefling** [comment]
I agree with @bdukes on this and think we should stick with the root project versioning strategy. The only other option that really makes sense to me is syncing up with the release of DNN. For example if we created a CD package for DNN 9.2 it would be 9.2.x.x and this would make things simple for matching it up to what version of DNN it was built for. The downside to this strategy is maintenance as we increment DNN versions.

My vote is for following what @bdukes is saying

**Comment by tpluscode** [comment]
I too prefer to keep the versions inline with the "real" ClientDependency. Let's make the current 1.9.2.x.

**Comment by SkyeHoefling** [comment]
Sounds good, I'll submit a PR later today

**Comment by SkyeHoefling** [comment]
Per conversation in #4 I am going to update the nuget package to be branded as DNN as advised by @tpluscode. Pull Request will be on it's way shortly

**Comment by SkyeHoefling** [comment]
@tpluscode since you have admin rights to appveyor can you provide the NuGet feed or location where we are publishing the generated nuspec file?

**Comment by tpluscode** [comment]
I was thinking to use the DNN's public MyGet feed but I see that it's not actually used as a source in DNN Platform. 

Maybe we should publish to NuGet.org instead?

@bdukes has access to a dnn profile there?

**Comment by SkyeHoefling** [comment]
I would recommend using our MyGet feed, this really shouldn't be published to the public NuGet.org

**Comment by bdukes** [comment]
I don't have access to DNN's org on the NuGet gallery (maybe @mitchelsellers does?)

I would agree that we shouldn't publish these to the NuGet gallery.  I'd probably lean towards using MyGet, unless it's significantly easier to setup AppVeyor hosting

**Comment by mitchelsellers** [comment]
I don't have it either @bdukes 

Looking at this, I'd agree, I think it should actually be a truly public NuGet item, rather than a private repo.

**Comment by SkyeHoefling** [comment]
@bdukes the AppVeyor nuget feed is super easy to setup, I do this all the time for the plugins I build for Xamarin. It does require enabling the feature from the AppVeyor UI configuration, I am not sure if we can configure it from the YAML file.

@mitchelsellers is there a use case I am missing? Are module developers using this fork outside of the Dnn Platform? If we are only using this in the Dnn Platform I do not see a need to add the fork to the public NuGet.org feed. If there are community members that would benefit from this being public then I would see a need but I may be missing something.

**Comment by mitchelsellers** [comment]
The use case is to avoid needing a private NUGet reference which would be restrictive in some environments as well as customizations that need this dependency.

Overall it would be more consistent to make it public.

Sent from my mobile device. Pardon any brevity or autocorrect mishaps

On May 17, 2018, at 22:13, Andrew Hoefling <notifications@github.com<mailto:notifications@github.com>> wrote:


@bdukes<https://github.com/bdukes> the AppVeyor nuget feed is super easy to setup, I do this all the time for the plugins I build for Xamarin. It does require enabling the feature from the AppVeyor UI configuration, I am not sure if we can configure it from the YAML file.

@mitchelsellers<https://github.com/mitchelsellers> is there a use case I am missing? Are module developers using this fork outside of the Dnn Platform? If we are only using this in the Dnn Platform I do not see a need to add the fork to the public NuGet.org<http://NuGet.org> feed. If there are community members that would benefit from this being public then I would see a need but I may be missing something.

**Comment by SkyeHoefling** [comment]
I don't have strong opinions on making it public or using the appveyor project feed or another private feed. With all of this being said I am curious what @bdukes thinks, if he is on board with putting it on the public NuGet.org feed than let's do that and continue to move forward.

Who do we need to potentially pull in that has access to the Dnn NuGet account? @tpluscode ? @ashishpd ?

**Comment by tpluscode** [comment]
FYI, I have just published Dnn.ClientDependency v1.9.2.7 on [MyGet](https://www.myget.org/feed/dnn-software-public/package/nuget/Dnn.ClientDependency/1.9.2.7).

Nothing stops us from moving to NuGet any time we decide to do that (and get the access 😬)
